//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamID: {0}{1}Login token: {2}.
        /// </summary>
        internal static string AddRes {
            get {
                return ResourceManager.GetString("AddRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.steampowered.com/IGameServersService/CreateAccount/v0001/?format=xml.
        /// </summary>
        internal static string AddURI {
            get {
                return ResourceManager.GetString("AddURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Server Manager by EasyCoding Team.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.steampowered.com/IGameServersService/GetAccountList/v0001/?key={0}&amp;format=xml.
        /// </summary>
        internal static string FetchURI {
            get {
                return ResourceManager.GetString("FetchURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching list of registered servers....
        /// </summary>
        internal static string MsgFt {
            get {
                return ResourceManager.GetString("MsgFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new server token....
        /// </summary>
        internal static string MsgGn {
            get {
                return ResourceManager.GetString("MsgGn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Steam API key entered in config file. Please open file stm.exe.config in text editor and enter your API key..
        /// </summary>
        internal static string NoAPIKey {
            get {
                return ResourceManager.GetString("NoAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option. Start program without any options to view help..
        /// </summary>
        internal static string UnknownOpt {
            get {
                return ResourceManager.GetString("UnknownOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0.
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stm.Resources.WelcomeMsg.txt.
        /// </summary>
        internal static string WelcomeFileName {
            get {
                return ResourceManager.GetString("WelcomeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###########################################################################
        ///#                    WELCOME TO SIMPLE SERVER MANAGER!                    #
        ///#         This console program will fetch or list tokens via API.         #
        ///#                                                                         #
        ///#          (C) 2005 - 2014 EasyCoding Team. All rights reserved.          #
        ///#             Original author: V1TSK (vitaly@easycoding.org).             #
        ///#                                                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax: stm &lt;generate | list &gt;.
        /// </summary>
        internal static string WlxMsg {
            get {
                return ResourceManager.GetString("WlxMsg", resourceCulture);
            }
        }
    }
}
